#!/bin/bash
# rich man's google repo tool
set -euo pipefail

if [ "$(basename "$PWD")" = "di_con_babyshark_enghost_yocto" ]; then
    echo "You are in the wrong dir, you must be in the parent directory of this to clone repos"
    exit 1
fi

SCRIPTDIR=$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")

(
    read -r
    while IFS=" " read -r FOLDER REV URL; do
        if [ -d "${FOLDER}" ]; then
            echo "${FOLDER} already exists, skipping"
            continue
        fi
        echo "Checking out ${URL} at revision ${REV} into ${FOLDER}"
        (set -x; git clone "${URL}" "${FOLDER}" && cd "${FOLDER}" && git checkout "${REV}")
    done
)< "${SCRIPTDIR}"/repositories.txt
