#!/bin/sh

IPCORE_SEARCH_PATH="/danteipcore"
IPCORE_EXTRACT_LOCATION="/tmp"

ip_core_tgz=$(find "$IPCORE_SEARCH_PATH" -name "ipcore*.tgz" | sort -V | tail -n 1)

if [ -z "${ip_core_tgz:-}" ] || [ ! -f "$ip_core_tgz" ]; then
    echo "Unable to locate dante ip core tgz"
    exit 1
fi

echo "Found latest IP core $ip_core_tgz, extracting"

tar -xzf "$ip_core_tgz" -C "$IPCORE_EXTRACT_LOCATION"

sh "$IPCORE_EXTRACT_LOCATION/ipcore/dante_package/start.sh zc702"
