#!/bin/sh
export SM_SERIAL_PORT=/dev/ttyPS1
export SM_IN_FIFO=/tmp/Q7_app_in
export SM_OUT_FIFO=/tmp/Q7_app_out
export SM_ETH_INTERFACE=eth0
export SM_PERSIST_FOLDER=/systempersist/serialmanager
export SM_START_APP_TCP="/usr/bin/Q7_app.bin -pT --v=2"
export SM_START_APP_UDP="/usr/bin/Q7_app.bin -pU"
export SM_KILL_APP="killall Q7_app.bin"
export SM_REBOOT_CMD="reboot -d -f"
# Here we will close our eyes and pray that hwmon0 and hwmon1 get enumerated in
# the order they are in the device tree :^)
export SM_ADC_HWMON_0=/sys/bus/i2c/devices/0-0048/hwmon/hwmon0/
export SM_ADC_HWMON_1=/sys/bus/i2c/devices/0-004a/hwmon/hwmon1/

serialclient
